---
title: "analysis"
author: "Alice Nzomo"
date: "2024-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warnings=F,message=F)
```

# histogram

```{r}
library(readr)

df <- read_csv("Credit Score  Data.csv")
head(df)



```
```{r}
x=df$Age
hist(x,main="histogram of age",col="purple")
```
```{r}
library(ggplot2)
ggplot(df,aes(Income))+geom_histogram(binwidth = 0.5)
```
#pipes in R using dplyr
```{r}
library(tidyverse)
df %>%select(Gender,Income) %>% #select extract one or more column()
  filter(Gender=="Female") %>% #filter extracts subset of data depending on a number of    conditions
  ggplot(aes(x=Gender,y=Income))+geom_bar(stat="identity")
```
```{r}
```


```{r}
d in dplyr stands for data frame while plyr is a package used to work with data set and data frames
functions include:select(),filter(),mutate(),group_by(),summarize(),arrange()
```
#mutate()used in addition of new variables
```{r}
df%>%mutate(d,+3=income +age)
```





#sample.n and sample()
For taking random specimen
```{r}

```
#Group by
```{r}
library(gapminder)

```
```{r}
gapminder
write.csv(gapminder,"gapminder.csv")
```
```{r}
gapminder %>% 
  group_by(continent) %>% 
  summarize(exp=mean(lifeExp))
```
```{r}
gapminder %>% 
  group_by(continent) %>% 
  summarize(exp=mean(lifeExp)) %>% 
  ggplot(aes(x=continent,y=exp,fill="blue"))+geom_bar(stat ="identity")+
  labs(title="Average life expectancy")
```
#Group by
```{r}
gapminder
write.csv(gapminder,"gapminder.csv")
```
```{r}
gapminder %>% 
  group_by(continent) %>% 
  summarise(exp=mean(lifeExp))
```
```{r}
gapminder %>% 
  group_by(continent) %>% 
  summarise(exp=mean(lifeExp)) %>% 
  ggplot(aes(x=continent,y=exp,fill="red"))+geom_bar(stat = "identity")+labs(title = "Averagee life expectancy")

```
#Head
```{r}
gapminder %>% head()
```
#sort and arrange by variable
```{r}
gapminder %>% #head(3)
  arrange(lifeExp)
```
#Filter
```{r}
gapminder %>% filter(country =="Rwanda")
```

#Select
```{r}
gapminder %>% select(country,year,lifeExp)
```



```{r}
gapminder %>% group_by(continent) %>% tally()
#table(gapminder$continent)
```



#Functions and Conditionals
```{r}
ages<-c(10,20,35,40,55,65,80,90,25,15)
age_bracket<-c()
for (age in ages) {
  if(age<18){x="young"}
  else if(age<40){x="mid"}
  else{x="old"}
  age_bracket<-c(age_bracket,x)
  
}
age_bracket
```
```{r}
gapminder %>% 
  mutate(period=ifelse(year<1950,"old",
                       ifelse(year<1970,"golden",
                              ifelse(year<2000,"vintage","millenium"))),
         population=pop/1000000) %>% 
  select(continent,year,period,population) %>% 
  group_by(continent,period) %>% 
  summarise(avg=mean(population))
```
#visualize the data
```{r}
library(ggthemes)
gapminder %>% 
  filter(year==2007) %>% 
  ggplot(aes(x=lifeExp,y=gdpPercap,color=continent))+
  geom_point()+
  facet_wrap(~continent,ncol=5)+
  theme_hc()

```








