---
title: "Introduction to R"
author: "Alice Nzomo"
date: "2024-05-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to vectors

vectors are the main data structure in R. Learn more about

* data structures


# Vectors


```{r}
10+34 # primitives -  numbers
FALSE #- Boolean
"alice" # strings

```


```{r}
names <-  c('alice','john','jochonia','hesus')
ages <- c(23,10,17,23)
truth <- c(FALSE,FALSE,TRUE)
print(names)
length(names)
# A Vector is an Array
# All elements in a vector are of the same data type,ex.Numeric and Character
# ALL values in R  are vectors
v1<-c(1,2,3,4,5)
```


```{r}
names(ages) = c('age1','age2',"age3","age4") # naming the vectors
ages['age4']
sum(ages)
sum(truth)
```

## factors

```{r}
height <- c("high",'low','mid','low','high')
height1 <- factor(height,levels = c('high','mid','low'))
print(height1)
sort(height1)
height[3]# extracting some level of informaion

```

```{r}
ages[ages>20] # this a subset of our data based on some logic
```

# Matrix / Matrices

```{r}
micro_econ <- c(70,87,40)
labor_econ <- c(40,37,50)
set_theory <- c(89,76,99)

lessons <-  matrix(c(micro_econ,labor_econ,set_theory),nrow = 3,byrow = TRUE)
rownames(lessons) <- c('micro_econ','labor_econ','set_theory')
colnames(lessons) <- c('first_year','second year','third year')

lessons
```
```{r}
lessons1 <- rbind(lessons,colSums(lessons))
lessons2 <- cbind(lessons1,rowMeans(lessons))
lessons2
```
# Lists

```{r}
x = list(micro_econ,height1)
x[[2]] # ndexing from the list  - extract the specific item  -  indexing starts at 1
```

```{r}
guests = c('Alice','john','eric')
gift   = c('cake','meat','music')
money  = c(2000,5000,500)
attendance = c(T,F,T)
speeches   = factor(guests,levels = c('Alice','eric','john'))

birthday = list(guests = guests,gifts = gift,contribution = money,attend = attendance,speech = speeches)
length(birthday)
```

```{r}
birthday[2:4]#slicing
birthday[5]
birthday$speech

```
# DATAFRAMES

```{r}

birthday <-  data.frame(birthday)
birthday
```

```{r}
birthday$gifts# extracting one column from a dataframe
birthday[1,2:3] # on the left we have the rows index and on right we have the columns index

```
# dataset ( its a dataframe and typically as a table)

```{r}
mtcars
min(mtcars$mpg)
max(mtcars$mpg)
mean(mtcars$mpg)
median(mtcars$mpg)
```

# descriptive statistics 

```{r}
hist(mtcars$mpg)
# descriptive statistics 
# measures of central tendency: mean,median,mode, IQR
# measures of dispersionand kurtosis: standard deviation, variance, IQR
# visualizations -  Histograms, barplots, piecharts,boxplots, stacked barplots, scatter plots etc
```
# control flows

```{r}
# for loop
# conditionals
```

# tidyverse and dplyr

```{r}
# data analysis and pipe in R
```

